version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./database/database.sqlite:/app/database/database.sqlite
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:YOUR_APP_KEY
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/database/database.sqlite
